### PR TITLE
Update project gallery styles

### LINKED ISSUE #142: Join button on project card not aligned to the bottom of the card

### PR DESCRIPTION
**Pull request by rmjordas**
I made some changes to the project gallery cards and a minor fix for the feedback button.

**Notes**:

- Use CSS Grids in `<Panel />` component.
- Remove project member pills*
- Make communication platform icons grayscale*
- **Fix join button to be aligned to the bottom of the card**
- Update join button styles*
- Fix minor style issues in feedback button  (margin fix)
- Add one (1) test for `<Card />` component 

*: Reason: detracts attention from title and description (I can revert the changes, if needed.)

Fixes  #142

### CODE REVIEW

**Comment by roymoran** [comment]
Screen Shot 2020-02-18 at 2 20 31 AM
Here are thoughts on the styling changes to the project card @rmjordas 
- I think we should keep the project member names. I see it as a good indicator that helps developers decide on a project. If there are 0 members on a project the developer might be surprised if he's the only one on the project. On the other hand a developer might only be looking for a project with a certain number of developers. Just feels like good information to give the developer when it comes to finding a project. With that said - they don't have to be pills if they are too distracting. They can take on a different style if needed. 
- Right now the slack/discord icon is used so the developer can join the workspace if it is always grayscale icon they won't know they can click it once they join. How about this -> the icon can be grayscale if the developer hasn't joined the project but should be a colored image if they are a member? This would actually help make it easier for the developer to understand that they can click the icon to join the workspace since there is a visible change in the icon.

Let me know what you think.

**Comment by GreenWithMV** [comment]
For the project member thing, an alternative could be to just display the # of current team members. Might be a little less distracting than the pills but provides some info on whether or not a project is active. I do think one thing that is hard is that right now my project has like "20" members but 16 of them never coded anything. Any thoughts on how to account for this? Are team leaders able to remove inactive team members?

**Comment by rickywid** [comment]
Here is my feedback

- I like how the platform icon is greyed out if they're not part of the project. I think this is good from a UI/UX perspective.
- I think it's important to leave the technologies used in the project so that members know what the tech stack is and they can decide whether or not the project would interest them. My only concern about this issue is if there's a laundry list of technologies, how would we display all of them.
- Same issue goes with displaying team members. I think it's a good idea to list team members but not sure how we will handle displaying a large team without cluttering the card.

**Comment by rmjordas** [comment]
Thanks for the feedback @roymoran @GreenWithMV @rickywid 

I agree, that showing the list of project members can be an indicator as to how active a project is. That said, I also agree with Ricky that large teams may result to a cluttered Card. So ultimately, I followed Green's suggestion by added a member count beside the Join button that looks like this:

Screenshot_2020-02-19 App

For the slack/discord icons, I fixed it to remove the grayscale if it is `clickable` (i.e. the user is a member).

Screenshot_2020-02-19 App(1)

**Pull request merged**
